import About from "../components/About";
import ContactMe from "../components/ContactMe";
import { DataProfile } from "../models/profile";
import Head from "next/head";
import Header from "../components/Header";
import type { NextPage } from "next";
import Profile from "../components/Profile";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperiencie from "../components/WorkExperiencie";
import json from "../db.json";

const Home: NextPage = () => {
  let data: DataProfile = json;

  return (
    <div
      className="bg-[#242424] text-white z-0 h-screen 
    overflow-scroll overflow-x-hidden 
    snap-y snap-mandatory "
    >
      <Head>
        <title>Chris Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/logo.png" />
      </Head>
      {/* Encabezado */}
      <Header />
      {/* Portada */}
      <section id="profile" className="snap-start">
        <Profile profile={data} />
      </section>
      {/* Acerca de mi */}
      <section id="about" className="snap-center">
        <About profile={data} />
      </section>
      {/* WorkExperience */}
      <section id="experience" className="snap-center">
        <WorkExperiencie experiences={data.experience} />
      </section>
      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills skills={data.skills} />
      </section>
      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects projects={data.projects} />
      </section>
      {/* Contact me */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
    </div>
  );
};

export default Home;
